### ISSUE TITLE
Windows build do not contain any binary

### ISSUE THREAD

**Issue by gsora** [ocminer/cpuminer-xzc#5]
As the title says, the windows link in the "release" tab doesn't contain any binary.

**Comment by ocminer** [comment]
As this in an open source project, you're free to download the source and compile a miner yourself, i'm on linux and not using windows at all, sorry !

**Comment by gsora** [comment]
Ok, since the README linked to a release I thought I'd find one there.

No problem on building one though.

Thanks for the reply.

**Comment by ocminer** [comment]
The Readme is a 1:1 copy from the original fork of the miner. It *should* compile fine with MSVC++ Community Edition though.
